image:
  file: .gitpod.Dockerfile

tasks:
  - before: |
      curl -sSL https://install.python-poetry.org | python3 -
      poetry config virtualenvs.create false
    init: | 
      poetry install
      poetry run jupyter contrib nbextension install --user
      poetry run jupyter nbextension enable --py widgetsnbextension
      poetry run jupyter nbextensions_configurator enable --user
    command: poetry run jupyter lab --NotebookApp.allow_origin="*"

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8888
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - yzhang.markdown-all-in-one
    - darkriszty.markdown-table-prettify
    - joaompinto.vscode-graphviz
  