# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      pyenv install 3.10.0
      pyenv local 3.10.0
      curl -sSL https://install.python-poetry.org | python3 -
    init: | 
      poetry install
      poetry run jupyter contrib nbextension install --user
      poetry run jupyter nbextension enable --py widgetsnbextension
      poetry run jupyter nbextensions_configurator enable --user
    command: poetry run jupyter lab

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
